name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if you're using that

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # this deploys your root folder (where index.html is)
        publish_branch: gh-pages
